---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: workloads-project
  source:
    repoURL: https://github.com/spkane/eks-crossplane-argocd
    targetRevision: HEAD
    path: argo-apps/eks-apps
    helm:
      values: |
        spec:
          destination:
            name: eks.cluster
  destination:
    name: eks.cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
