---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-cluster 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads-project
  source:
    repoURL: https://github.com/spkane/eks-crossplane-argocd
    targetRevision: HEAD
    path: argo-apps/workloads/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
