---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # This is here to ignore k8s AggregatedRoles diffs as they will always look out of sync
  resource.compareoptions: |
    ignoreAggregatedRoles: true
---
#
# If you are connecting repositories via SSH, ArgoCD will need to know the SSH known hosts public key of the repository servers.
# This ConfigMap contains a single key/value pair, with ssh_known_hosts as the key and the actual public keys of the SSH servers as data.
# The public key(s) of each single repository server ArgoCD will connect via SSH must be configured,
# otherwise the connections to the repository will fail. There is no fallback.
# The public key can be obtained from an existing ~/.ssh/known_hosts or using a CLI utility as follows: 'ssh-keyscan github.com'
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-ssh-known-hosts-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  ssh_known_hosts: |
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
---
#
# Helm Repositories
# Non standard Helm Chart repositories have to be registered
# Each repository must have 'url', 'type' and 'name' fields
#
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: prometheus-argocd
  url: https://prometheus-community.github.io/helm-charts
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: grafana-argocd
  url: https://grafana.github.io/helm-charts
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: crossplane-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: crossplane-argocd
  url: https://charts.crossplane.io/stable
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: eks-crossplane-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/spkane/eks-crossplane-argocd
