---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads-project
  source:
    repoURL: https://github.com/spkane/eks-crossplane-argocd
    targetRevision: HEAD
    path: argo-apps/workloads/monitoring
    helm:
      releaseName: observability
      valueFiles:
      - grafana-values.yaml
      - prometheus-values.yaml
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
