apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgAfbZtAgCttwsO5aCQFRYoKRQGnBJSxKgpMSEsaoPiEBLStH1jymh8EetjZcsJUt+jjGTBXbH0VFCAdWV72X3fbmFXaLLvmdEqBhRfF5mdS66VS6aec0+mTYzfo3BRt5QbJEO42wCGrUZayryc8ni2i+TlydGcjom1fn9idM/IQ1WRrqDwwN9grtA2JCyf8u0u1vpPbmaDd7h0ibw1kGb6MNPCqSnerYJ2+FuIgoe6wN3AxV5LjeH76YrAMHLvnIPs40Hbb7jkeg4FauIAm27wP8SnvE9hRX9c0F6yVSrf2sE/rV3lLlOmDJYz+PdvQGstsUeOIlI4sqASSenXKC6Y+BzOEN3SKC4nXg0BedQQMiVn3o1qcfKdLHmXLAXcsyhiVUxldKEj2xeJ6PlhR8aYmI5Teszv/6/BCOSGUyt21+SbskyIMy+O0G+gaHtPQNFyYTG9zh6pFg5vd8rnM1PYPUILPXo1nhkKOrF5HHMOW3bPQwpqXuZ4oFH8gzYeuClELgvoUckmpwr/vKGLxId2zYvu/cggSnn/2aR0XW+2W6DO+qYMO/O22DKFfxKt7AmCTNKncJxTFldOjDaOw2a0NDmzT1YTunl0JsB7lvzRZ6/9LM5SeodtMeoSdJBPbcR515txh7du0Pzj0jg2Xz5VaPUqGy+WjZr6CIpSwBUctdCK76CXugdOYDTgdRwSv1XLR0uQQm3mfhmhrlPwkA/TkKKBF7I0+IMPSceVKxwONhc6P+GX0g/UjjiKhsluMqSnsb+6ObKs7drapG8CDru5sJUek+b4dRGsK7pWUFn+MuKOn1LqT5MO0Uow9T3iUoJzsH8pNjgs3iBQJbEDqdlcOgw==
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque

