apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
spec:
  encryptedData:
    # This is not a valid credential
    credentials: AgCJux/DvhjKxtBiGMGq9DJcO4yZkgAqRJYxDV0Nw8fdsuc53Agk/1SfrGBvhx==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

