apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgAHsdYIxU8yzFU8hpICIkR602pyYbipVO39ZowKh9cn+ZP1P2P3n/7ig/u4BP5gnVnwdBzPITsC4xrB9hnLYOL3epEJ5Q5Ur/5Gm0bkHMrhf+huL0VSotlWAJUNxX8B05zfdONt7SsQcr/Y3wtbHE20VTyM/gW9zobonu2XiMVZ/ywNp6Dwnk0z/p7pDOb5TcACQNgXYAuUz2dbRtOm1uCSlxOMHsAU3LmYtS4zXl6vrEchVJZ7DKU/HKVx65AczICwwlaeVqGx5JZavXx+AJVB3g0Qkt8vbXt1e+At6vvxnuEzx5Xvzn5acSx/FHCtgQB1RIDzOrn/CmLyLswJPY0cjFPCTzCGPt7Gg/Jrbyqdd4Qr5+s4Gx1zIqoIGEvaXAAuTyuCqk/YJjKMEkgtadHmSxuJC/sM6BaEuRFg0ct46JTKTzmV3AOnDAMAwEvaUnwgVxpj4yPGDwGgf7o76XfbHFukv/QorW+lLOTpRdQJvDIvcauTGjD4SEnQUinHlJSv/kZm24ffcBkmX9KlAPFsIJdEJXZGeGEjJRbqOoY3Q+1f3zYMzw6vCr3V9367vaOwMWn707iq4GPUspZDqz22Kh1DNqk/V4S65gDDPdx9SqhaZyiM1Y8cCFG80/vq69QU+Ll6Gf1y0UPCiIznn76Xz8A8zYAUY5mF3e+XmS94vKwHdBu2xMzz+s6mbK+DI4YRaOJa38e87ZgAWJ1NzoKD8n+/0rIvaGwqgYoowFapd0RBAeJQBzS2A4O7ZvqzC4FndvUG3a3MJO05Y3gv6h+8kvEK6vpy9Wxh95UIicHE3/aqfHkPwY2wxpI2FxdGH7G4Ix73z95RkSvpCi67IJlrLA==
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque

